// Generator module - Code Generator
// VAIXLNS Builder v0.1

use crate::ir::{CanonicalSpec, CanonicalId};
use crate::planner::BuildPlan;

pub struct CodeGenerator {
    spec: CanonicalSpec,
    plan: BuildPlan,
}

impl CodeGenerator {
    pub fn new(spec: CanonicalSpec, plan: BuildPlan) -> Self {
        Self { spec, plan }
    }

    pub fn generate(&self) -> String {
        let mut output = String::new();
        
        output.push_str("// ============================================================\n");
        output.push_str("// Generated by VAIXLNS Builder v0.1\n");
        output.push_str("// DO NOT EDIT MANUALLY - This file is automatically generated\n");
        output.push_str("// ============================================================\n\n");
        
        output.push_str("// Build Information:\n");
        output.push_str(&format!("// Total Phases: {}\n", self.plan.phases.len()));
        output.push_str(&format!("// Total Nodes: {}\n", self.plan.total_nodes));
        output.push_str("//\n\n");

        for (id, entity) in &self.spec.entities {
            output.push_str(&self.generate_entity(id, entity));
        }

        output.push_str(&self.generate_runtime());
        output.push_str(&self.generate_main());
        output.push_str(&self.generate_tests());

        output
    }

    fn generate_entity(&self, id: &CanonicalId, entity: &crate::ir::CanonicalEntity) -> String {
        let mut output = String::new();
        let struct_name = id.0.replace('.', "_");
        
        output.push_str(&format!("/// Entity: {}\n", id));
        output.push_str(&format!("/// Domain: {}\n", entity.domain));
        output.push_str(&format!("/// Kind: {}\n", entity.kind));
        output.push_str("#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n");
        output.push_str(&format!("pub struct {} {{\n", struct_name));
        
        for provide in &entity.provides {
            let field_type = match provide.as_str() {
                "identity" => "String",
                "timebase" => "u64",
                "execute" => "fn() -> String",
                "replay" => "fn() -> String",
                "state" => "String",
                "hash" => "String",
                "signature" => "String",
                "laws" => "Vec<String>",
                "rules" => "Vec<String>",
                "metrics" => "std::collections::HashMap<String, f64>",
                "version" => "String",
                "name" => "String",
                _ => "String",
            };
            output.push_str(&format!("    pub {}: {},\n", provide, field_type));
        }
        
        output.push_str("}\n\n");
        
        output.push_str(&format!("impl Default for {} {{\n", struct_name));
        output.push_str("    fn default() -> Self {\n");
        output.push_str("        Self {\n");
        for provide in &entity.provides {
            let default = match provide.as_str() {
                "identity" => "\"unknown\".to_string()",
                "timebase" => "0",
                "execute" => "|| \"executed\".to_string()",
                "replay" => "|| \"replayed\".to_string()",
                "state" => "\"initial\".to_string()",
                "hash" => "\"0x0000\".to_string()",
                "signature" => "\"unsigned\".to_string()",
                "laws" => "Vec::new()",
                "rules" => "Vec::new()",
                "metrics" => "std::collections::HashMap::new()",
                "version" => "\"0.1.0\".to_string()",
                "name" => "\"unnamed\".to_string()",
                _ => "\"\".to_string()",
            };
            output.push_str(&format!("            {}: {},\n", provide, default));
        }
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");
        
        output
    }

    fn generate_runtime(&self) -> String {
        let mut output = String::new();
        
        output.push_str("// ============================================================\n");
        output.push_str("// Runtime Structure\n");
        output.push_str("// ============================================================\n\n");
        
        output.push_str("#[derive(Debug, Clone)]\n");
        output.push_str("pub struct Runtime {\n");
        
        for id in self.spec.entities.keys() {
            let field_name = id.0.replace('.', "_");
            let struct_name = id.0.replace('.', "_");
            output.push_str(&format!("    pub {}: {},\n", field_name, struct_name));
        }
        
        output.push_str("    pub metadata: RuntimeMetadata,\n");
        output.push_str("    pub status: RuntimeStatus,\n");
        output.push_str("}\n\n");

        output.push_str("#[derive(Debug, Clone)]\n");
        output.push_str("pub struct RuntimeMetadata {\n");
        output.push_str("    pub version: String,\n");
        output.push_str("    pub genesis_hash: String,\n");
        output.push_str("    pub build_id: String,\n");
        output.push_str("    pub phases: Vec<String>,\n");
        output.push_str("    pub entities: Vec<String>,\n");
        output.push_str("    pub created_at: String,\n");
        output.push_str("    pub builder_version: String,\n");
        output.push_str("}\n\n");

        output.push_str("#[derive(Debug, Clone)]\n");
        output.push_str("pub struct RuntimeStatus {\n");
        output.push_str("    pub ready: bool,\n");
        output.push_str("    pub running: bool,\n");
        output.push_str("    pub version: String,\n");
        output.push_str("    pub entities: Vec<String>,\n");
        output.push_str("    pub phases: Vec<String>,\n");
        output.push_str("    pub entities_count: usize,\n");
        output.push_str("    pub uptime: u64,\n");
        output.push_str("}\n\n");

        output.push_str("impl Runtime {\n");
        output.push_str("    pub fn new() -> Self {\n");
        output.push_str("        Self {\n");
        
        for id in self.spec.entities.keys() {
            let field_name = id.0.replace('.', "_");
            let struct_name = id.0.replace('.', "_");
            output.push_str(&format!("            {}: {}::default(),\n", field_name, struct_name));
        }
        
        output.push_str("            metadata: RuntimeMetadata {\n");
        output.push_str("                version: \"0.1.0\".to_string(),\n");
        output.push_str("                genesis_hash: \"GENESIS_001\".to_string(),\n");
        output.push_str("                build_id: \"BUILD_001\".to_string(),\n");
        output.push_str("                phases: vec![\n");
        for phase in &self.plan.phases {
            output.push_str(&format!("                    \"Phase {}: {}\".to_string(),\n", 
                phase.index, phase.kind));
        }
        output.push_str("                ],\n");
        output.push_str("                entities: vec![\n");
        for id in self.spec.entities.keys() {
            output.push_str(&format!("                    \"{}\".to_string(),\n", id.0));
        }
        output.push_str("                ],\n");
        output.push_str("                created_at: chrono::Utc::now().to_rfc3339(),\n");
        output.push_str("                builder_version: env!(\"CARGO_PKG_VERSION\").to_string(),\n");
        output.push_str("            },\n");
        output.push_str("            status: RuntimeStatus {\n");
        output.push_str("                ready: true,\n");
        output.push_str("                running: false,\n");
        output.push_str("                version: \"0.1.0\".to_string(),\n");
        output.push_str("                entities: vec![\n");
        for id in self.spec.entities.keys() {
            output.push_str(&format!("                    \"{}\".to_string(),\n", id.0));
        }
        output.push_str("                ],\n");
        output.push_str("                phases: vec![\n");
        for phase in &self.plan.phases {
            output.push_str(&format!("                    \"Phase {}: {}\".to_string(),\n", 
                phase.index, phase.kind));
        }
        output.push_str("                ],\n");
        output.push_str(&format!("                entities_count: {},\n", self.spec.entities.len()));
        output.push_str("                uptime: 0,\n");
        output.push_str("            },\n");
        output.push_str("        }\n");
        output.push_str("    }\n\n");

        output.push_str("    pub fn start(&mut self) {\n");
        output.push_str("        println!(\"╔════════════════════════════════════════════╗\");\n");
        output.push_str("        println!(\"║   VAIXLNS Runtime v{} - Starting           ║\", self.metadata.version);\n");
        output.push_str("        println!(\"╚════════════════════════════════════════════╝\");\n");
        output.push_str("        println!();\n");
        output.push_str("        println!(\"🔧 Initializing runtime...\");\n");
        output.push_str("        println!(\"📦 Genesis Hash: {}\", self.metadata.genesis_hash);\n");
        output.push_str("        println!(\"📋 Build ID: {}\", self.metadata.build_id);\n");
        output.push_str("        println!(\"📊 Phases: {}\", self.metadata.phases.len());\n");
        output.push_str("        println!(\"📊 Entities: {}\", self.metadata.entities.len());\n");
        output.push_str("        println!(\"🕐 Created: {}\", self.metadata.created_at);\n");
        output.push_str("        println!();\n");
        output.push_str("        self.status.running = true;\n");
        output.push_str("        println!(\"✅ Runtime started successfully!\");\n");
        output.push_str("    }\n\n");

        output.push_str("    pub fn stop(&mut self) {\n");
        output.push_str("        println!(\"🛑 Stopping runtime...\");\n");
        output.push_str("        self.status.running = false;\n");
        output.push_str("        println!(\"✅ Runtime stopped.\");\n");
        output.push_str("    }\n\n");

        output.push_str("    pub fn status(&self) -> &RuntimeStatus {\n");
        output.push_str("        &self.status\n");
        output.push_str("    }\n\n");

        output.push_str("    pub fn get_entity(&self, name: &str) -> Option<&dyn std::any::Any> {\n");
        output.push_str("        match name {\n");
        for id in self.spec.entities.keys() {
            let field_name = id.0.replace('.', "_");
            output.push_str(&format!("            \"{}\" => Some(&self.{} as &dyn std::any::Any),\n", id.0, field_name));
        }
        output.push_str("            _ => None,\n");
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");
        
        output
    }

    fn generate_main(&self) -> String {
        let mut output = String::new();
        
        output.push_str("// ============================================================\n");
        output.push_str("// Main Entry Point\n");
        output.push_str("// ============================================================\n\n");
        
        output.push_str("fn main() {\n");
        output.push_str("    let mut runtime = Runtime::new();\n");
        output.push_str("    runtime.start();\n");
        output.push_str("    \n");
        output.push_str("    let status = runtime.status();\n");
        output.push_str("    println!();\n");
        output.push_str("    println!(\"📊 Runtime Status:\");\n");
        output.push_str("    println!(\"   Ready: {}\", status.ready);\n");
        output.push_str("    println!(\"   Running: {}\", status.running);\n");
        output.push_str("    println!(\"   Version: {}\", status.version);\n");
        output.push_str("    println!(\"   Entities: {} ({})\", status.entities_count, status.entities.len());\n");
        output.push_str("    for entity in &status.entities {\n");
        output.push_str("        println!(\"     - {}\", entity);\n");
        output.push_str("    }\n");
        output.push_str("    println!(\"   Phases: {}\", status.phases.len());\n");
        output.push_str("    for phase in &status.phases {\n");
        output.push_str("        println!(\"     - {}\", phase);\n");
        output.push_str("    }\n");
        output.push_str("    \n");
        output.push_str("    runtime.stop();\n");
        output.push_str("}\n\n");
        
        output
    }

    fn generate_tests(&self) -> String {
        let mut output = String::new();
        
        output.push_str("// ============================================================\n");
        output.push_str("// Generated Tests\n");
        output.push_str("// ============================================================\n\n");
        
        output.push_str("#[cfg(test)]\n");
        output.push_str("mod tests {\n");
        output.push_str("    use super::*;\n\n");
        
        output.push_str("    #[test]\n");
        output.push_str("    fn test_runtime_creation() {\n");
        output.push_str("        let runtime = Runtime::new();\n");
        output.push_str("        let status = runtime.status();\n");
        output.push_str("        assert!(status.ready);\n");
        output.push_str("        assert!(!status.running);\n");
        output.push_str("        assert_eq!(status.version, \"0.1.0\");\n");
        output.push_str("        assert!(!status.entities.is_empty());\n");
        output.push_str("    }\n\n");
        
        output.push_str("    #[test]\n");
        output.push_str("    fn test_runtime_start_stop() {\n");
        output.push_str("        let mut runtime = Runtime::new();\n");
        output.push_str("        runtime.start();\n");
        output.push_str("        assert!(runtime.status().running);\n");
        output.push_str("        runtime.stop();\n");
        output.push_str("        assert!(!runtime.status().running);\n");
        output.push_str("    }\n\n");
        
        for id in self.spec.entities.keys() {
            let struct_name = id.0.replace('.', "_");
            output.push_str(&format!("    #[test]\n"));
            output.push_str(&format!("    fn test_{}_default() {{\n", struct_name));
            output.push_str(&format!("        let entity = {}::default();\n", struct_name));
            output.push_str(&format!("        let _ = entity;\n"));
            output.push_str(&format!("    }}\n\n"));
        }
        
        output.push_str("}\n");
        
        output
    }
}
